### ISSUE TITLE
Float range support

### ISSUE THREAD

**Issue by danchoi** [gregwebs/haskell-sphinx-client#13]
I made a patch for this, but I am just winging it. Can someone review and comment?

https://github.com/danchoi/haskell-sphinx-client/commit/7d1785e7ab5f28b94f6c1b5b3d46bfd88bf293dd#diff-b168b2a6cd60654b9a5a4ab41b183184R20

**Comment by gregwebs** [comment]
That makes sense. You should try it out and see if it works.

**Comment by danchoi** [comment]
I made one change and tested this. It seems to work. The test case setup is at https://github.com/danchoi/sphinx-test

**Comment by gregwebs** [comment]
Send a pull request then! And if you can, dump the sphinx-test source into an example subdirectory for this project.

**Comment by danchoi** [comment]
OK I'll dump the test source into a directory.

**Comment by paul-rouse** [comment]
This was completed in #14, which was merged but appears not to have been released.  It is in the release which has just been made - 0.6.0.2
