### ISSUE TITLE
Add back into stackage?

### ISSUE THREAD

**Issue by paul-rouse** [gregwebs/haskell-sphinx-client#16]
`sphinx` has dropped out of stackage nightly because of https://github.com/fpco/stackage/commit/dce0852ea7c091631b3322c70b92a0592fa1a591 (Michael Snoyman had it listed in his group of packages).  I'd quite like to see it retained in stackage, so is there any reason not to put it back?  Do you want to do it, or shall I list it under me?

**Comment by gregwebs** [comment]
Hey, sorry for missing this. Would be great if you can add it.

**Comment by paul-rouse** [comment]
Done in https://github.com/fpco/stackage/pull/1647.  It's listed under me as far as stackage is concerned - if you want me really to be a co-maintainer, just say!

**Comment by gregwebs** [comment]
That would be great- I can barely keep up with my other packages. I added you as a collaborator to github.

**Comment by paul-rouse** [comment]
I'm very pleased to help, and I've accepted the github invitation!  Obviously I'll ask you to review if anything big crops up.  Anyway, let's close this issue now, since my PR in stackage has passed its tests.
