### ISSUE TITLE
Running too many queries with runQueries at once will raise "exception: too few bytes."

### ISSUE THREAD

**Issue by adimit** [gregwebs/haskell-sphinx-client#9]
(I'm reporting this more as a reminder to myself and so that people can find it who might get bitten by this bug. I'll have to try and fix this later, but it might not be trivial.)

(There's also #4, which might be similar to this, but it's definitely a different bug.)

The title already says it all: if you run *more than 32 queries* at once with `runQueries`, you will get this nasty exception.

    > let q = Query { queryString = "foo", queryIndexes = "*", queryComment = "" }
    > runQueries searchConf (replicate 32 q)
    -- … good stuff
    > runQueries searchConf (replicate 33 q)
    Error 1 "*** Exception: too few bytes. Failed reading at byte position 1650549796

This appears to happen before queries get sent to sphinx, so it seems a problem on our end. I won't have time to fix this immediately, but it's on my TODO-list. My own application frequently sends a bunch of queries like this, so I'll have to work around it (it's easy, just use `Data.List.Split`'s [`chunksOf`](http://hackage.haskell.org/packages/archive/split/0.2.1.1/doc/html/Data-List-Split.html) function.)

I'll probably have time to look at it, say, next weekend or so, hopefully earlier.

**Comment by paul-rouse** [comment]
I know this is really old!  The fix d61e861276f84d00da116eae583da4cfd60f4362 I have just put in for #17 solves this one too.  The error message now contains the much more helpful "bad multi-query count 33 (must be in 1..32 range)"!  I think we can close this issue now.
